swagger: "2.0"
info:
  version: "1.0.0"
  title: "Popup Dev Test (CSS Modal)"
  description: |
    <style>
      .modal-bg {
        display: none;
        position: fixed; top: 0; left: 0; width: 100%; height: 100%;
        background: rgba(0,0,0,0.7); 
      }
      .modal-box {
        background: white; padding: 20px; width: 300px;
        margin: 150px auto; border-radius: 8px;
      }
      #show:checked ~ .modal-bg { display: block; }
    </style>

    <label for="show" style="cursor:pointer;padding:10px;background:#0099ff;color:white;border-radius:5px;">
      Open Popup
    </label>
    <input type="checkbox" id="show" style="display:none">

    <div><script>alert(1)</script></div>
    <div class="modal-bg">
      <div class="modal-box">
        <h3>Popup Aman</h3>
        <p>Ini popup untuk testing dev tanpa XSS.</p>
        <label for="show" style="cursor:pointer;">Close</label>
      </div>
    </div>

paths:
  /:
    get:
      responses:
        200:
          description: OK
